### Get all tasks
GET http://localhost:3000/tasks

### Get task by id
GET http://localhost:3000/tasks/66875cb8-24fc-4317-a72b-6519d6fcf747

### Create a task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "1. Learn Nest",
  "description": "1. from Udemy course"
}

### Delete task by id
DELETE http://localhost:3000/tasks/39c6453c-285e-4af6-a675-a95594947498

### Update task by id
PATCH http://localhost:3000/tasks/885b2f67-6b33-4f66-98f2-b26fdefc040a/status
Content-Type: application/json

{
  "status": "OPEN"
}

### Get all tasks with status or search filter
GET http://localhost:3000/tasks?search=next